api:
  devices_to_use:
    - cuda:0
    - cpu
    - mps

loguru:
  LOG_FILE_NAME: '/LOGS/loguru.log'
  LOG_ROTATION: '22 MB'
  LOG_RETENTION: '100 days'

llm:
  LLM_API_KEY: '-'
  LLM_API_URL: ''
  LLM_MODEL: 'gpt-4o-mini'
  temperature: 0.0
  top_p: 0.5