api:
  devices_to_use:
    - cuda:0
    - cpu
    - mps

loguru:
  LOG_FILE_NAME: '/LOGS/loguru.log'
  LOG_ROTATION: '22 MB'
  LOG_RETENTION: '100 days'

search:
  SEARCH_URL:  '${SEARCH_URL}'
  search_by: hybrid
  top_k: 5

llm:
  LLM_API_KEY: '${LLM_API_KEY}'
  LLM_API_URL: http://host.docker.internal:8777
  SYSTEM_PROMPT: "

  You are a highly capable language assistant with remarkable skillset on the following:

    - History and mechanics of computer games.

    - Well-versed in many films.

    - Skilled at providing user support and guidance for complex systems (e.g. user portals, 
      databases, or other technical domains).
  
    - Scientific facts and general historical facts"
  LLM_MODEL: 'gpt-4o-mini'
  temperature: 0.22
  max_tokens: 4096
  top_p: 10

sgi:
  HOST: "0.0.0.0"
  PORT: 7777
  WORKERS_COUNT: 1
  AUTO_RELOAD: true
  TIMEOUT: 420
  WSGI_APP: "src.api.application:app"
  WORKER_CLASS: "uvicorn.workers.UvicornWorker"

telegram:
  TELEGRAM_BOT_TOKEN: '${TELEGRAM_BOT_TOKEN}'
  TELEGRAM_BOT_WEBHOOK_URL: '${TELEGRAM_BOT_WEBHOOK_URL}'
  TELEGRAM_BOT_MODE: '${TELEGRAM_BOT_MODE}'
  edit_interval: 1
  initial_token_threshold: 5
  typing_interval: 5
