extern:
  models:
    - gpt-4-0613
    - gpt-4-0314
  save_extern_path: ".data/external"

api:
  devices_to_use:
    - cuda:0
    - cpu
    - mps
  openai_model_path: gpt-4o-mini

log:
  log_grafana_metrics: true
