version: '3.8'

services:
  rethinkdb:
    image: rethinkdb:latest
    container_name: llm_bot_rethinkdb
    environment:
      - RETHINKDB_DB=${RETHINKDB_DB}
    restart: unless-stopped
    ports:
      - "28015:28015"
      - "8080:8080"
    volumes:
      - rethinkdb_data:/data:rw

  llm_bot_backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    # restart: on-failure
    ports:
      - "${SGI_PORT}:${SGI_PORT}"
    volumes:
      - ./src:/opt/app-root/src:rw
      - ./LOGS:/LOGS:rw
      - ./config.yaml:/opt/app-root/config.yaml:ro

volumes:
  rethinkdb_data:
    external: false
