version: '3.8'

services:
  llm_bot_postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgvolume:/var/lib/postgresql/data:rw

  llm_bot_backend:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "7420:7420"
    volumes:
      - ./src:/opt/app-root/src:rw
  
volumes:
  pgvolume:
    external: false